"""Add username field to User model

Revision ID: add_username_to_users
Revises: 067be40dce55
Create Date: 2024-12-19 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_username_to_users"
down_revision: Union[str, None] = "067be40dce55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add username column to users table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_users_username", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove username column from users table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_username", type_="unique")
        batch_op.drop_column("username")
    # ### end Alembic commands ###
