"""Add job_configurations table

Revision ID: e0f6efc3e8c1
Revises: 067be40dce55
Create Date: 2025-05-31 19:52:09.616837

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from core.models.appointment import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "e0f6efc3e8c1"
down_revision: Union[str, None] = "067be40dce55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("archive_configuration_id", sa.Integer(), nullable=False),
        sa.Column("archive_window_days", sa.Integer(), nullable=False),
        sa.Column("schedule_type", sa.String(length=16), nullable=False),
        sa.Column("schedule_hour", sa.Integer(), nullable=False),
        sa.Column("schedule_minute", sa.Integer(), nullable=False),
        sa.Column("schedule_day_of_week", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_configuration_id"],
            ["archive_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_configurations_archive_configuration_id"),
        "job_configurations",
        ["archive_configuration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_configurations_user_id"),
        "job_configurations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_job_configurations_user_id"), table_name="job_configurations"
    )
    op.drop_index(
        op.f("ix_job_configurations_archive_configuration_id"),
        table_name="job_configurations",
    )
    op.drop_table("job_configurations")
    # ### end Alembic commands ###
