"""empty message

Revision ID: f44e88f7e0bc
Revises: e354143baf8f
Create Date: 2025-05-29 21:04:45.020134

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f44e88f7e0bc"
down_revision: Union[str, None] = "e354143baf8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointments", sa.Column("calendar_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointments", "calendar_id")
    # ### end Alembic commands ###
