"""Add NotificationClass model and FK to NotificationPreference

Revision ID: 2764bb07609a
Revises: 6d95d9e6f148
Create Date: 2025-05-26 18:10:50.472918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2764bb07609a'
down_revision = '6d95d9e6f148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'notification_classes', ['notification_class'], ['key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('notification_classes')
    # ### end Alembic commands ###
