"""Add transaction_id to Notification

Revision ID: 2e62aaa5b2af
Revises: a1ba2b1f6655
Create Date: 2025-05-26 17:18:03.805045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e62aaa5b2af'
down_revision = 'a1ba2b1f6655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
