"""Add pct_complete, progress, state to Notification

Revision ID: 54d9535ac8bc
Revises: 2e62aaa5b2af
Create Date: 2025-05-26 17:23:02.679864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d9535ac8bc'
down_revision = '2e62aaa5b2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pct_complete', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('progress')
        batch_op.drop_column('pct_complete')

    # ### end Alembic commands ###
