"""Add NotificationPreference model for user notification channel preferences

Revision ID: 6d95d9e6f148
Revises: 54d9535ac8bc
Create Date: 2025-05-26 17:56:11.764332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d95d9e6f148'
down_revision = '54d9535ac8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_class', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
