"""add ms_token_cache to user

Revision ID: 49ebd13a64dd
Revises: 60e5dca644c0
Create Date: 2025-05-28 22:45:34.487376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ebd13a64dd'
down_revision: Union[str, None] = '60e5dca644c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ms_token_cache', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ms_token_cache')
    # ### end Alembic commands ###
