"""add ms_event_id to appointment

Revision ID: b5040f7d1711
Revises: d5cb2da0c3f7
Create Date: 2025-05-27 19:47:15.524972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5040f7d1711'
down_revision: Union[str, None] = 'd5cb2da0c3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('ms_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'ms_event_id')
    # ### end Alembic commands ###
