"""add recurrence and ms_event_data to appointment

Revision ID: d5cb2da0c3f7
Revises: 09ddf2132667
Create Date: 2025-05-27 19:25:24.924503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5cb2da0c3f7'
down_revision: Union[str, None] = '09ddf2132667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('recurrence', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ms_event_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'ms_event_data')
    op.drop_column('appointments', 'recurrence')
    # ### end Alembic commands ###
