"""add action_log to track request for user's to complete

Revision ID: e4638bd4c701
Revises: b5040f7d1711
Create Date: 2025-05-28 13:09:47.590159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4638bd4c701'
down_revision: Union[str, None] = 'b5040f7d1711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('show_as', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('sensitivity', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('location', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('attendees', sa.JSON(), nullable=True))
    op.add_column('appointments', sa.Column('organizer', sa.JSON(), nullable=True))
    op.add_column('appointments', sa.Column('categories', sa.JSON(), nullable=True))
    op.add_column('appointments', sa.Column('importance', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('reminder_minutes_before_start', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('is_all_day', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('response_status', sa.JSON(), nullable=True))
    op.add_column('appointments', sa.Column('series_master_id', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('online_meeting', sa.JSON(), nullable=True))
    op.add_column('appointments', sa.Column('body_content', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('body_content_type', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('body_preview', sa.String(), nullable=True))
    op.drop_column('appointments', 'is_archived')
    op.drop_column('appointments', 'is_out_of_office')
    op.drop_column('appointments', 'is_private')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_private', sa.BOOLEAN(), nullable=True))
    op.add_column('appointments', sa.Column('is_out_of_office', sa.BOOLEAN(), nullable=True))
    op.add_column('appointments', sa.Column('is_archived', sa.BOOLEAN(), nullable=True))
    op.drop_column('appointments', 'body_preview')
    op.drop_column('appointments', 'body_content_type')
    op.drop_column('appointments', 'body_content')
    op.drop_column('appointments', 'online_meeting')
    op.drop_column('appointments', 'series_master_id')
    op.drop_column('appointments', 'response_status')
    op.drop_column('appointments', 'is_all_day')
    op.drop_column('appointments', 'reminder_minutes_before_start')
    op.drop_column('appointments', 'importance')
    op.drop_column('appointments', 'categories')
    op.drop_column('appointments', 'organizer')
    op.drop_column('appointments', 'attendees')
    op.drop_column('appointments', 'location')
    op.drop_column('appointments', 'sensitivity')
    op.drop_column('appointments', 'show_as')
    # ### end Alembic commands ###
