name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  tests:
    name: "${{ matrix.group.name }} (Python ${{ matrix.python-version }})"
    runs-on: ubuntu-latest
    environment: Testing
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']  # TODO: Re-enable 3.13 when asyncpg supports it
        group:
          - name: unit
            marker: "unit"
            cov_flag: "unit"
          - name: integration
            marker: "integration"
            cov_flag: "integration"
          - name: utilities
            marker: "utility or dev"
            cov_flag: "utilities"

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Create virtual environment
      run: |
        python -m venv .venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Upgrade pip
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        pip install -e .[dev]

    - name: Set up test environment
      run: |
        # Create instance directory for any file-based operations
        mkdir -p instance
      env:
        APP_ENV: testing
        DATABASE_URL: "sqlite:///:memory:"
        CORE_DATABASE_URL: "sqlite:///:memory:"
        LOG_LEVEL: INFO
        OTEL_SDK_DISABLED: true

    - name: Run ${{ matrix.group.name }} tests with coverage
      run: |
        source .venv/bin/activate
        python -m pytest -v -m "${{ matrix.group.marker }}" \
          --cov=src \
          --cov-report=xml:coverage.xml \
          --cov-report=html \
          --cov-report=term-missing \
          --tb=short \
          --junitxml=test-results.xml
      env:
        APP_ENV: testing
        DATABASE_URL: "sqlite:///:memory:"
        CORE_DATABASE_URL: "sqlite:///:memory:"
        LOG_LEVEL: INFO
        OTEL_SDK_DISABLED: true

    - name: Upload coverage reports to Codecov (${{ matrix.group.cov_flag }})
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: ${{ matrix.group.cov_flag }}
        name: codecov-${{ matrix.group.cov_flag }}
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ matrix.group.name }}-${{ matrix.python-version }}
        path: htmlcov/

    - name: Upload test results (JUnit XML)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.group.name }}-${{ matrix.python-version }}
        path: |
          .coverage
          coverage.xml
          test-results.xml
